version: "3.9"
services:
  record-stream:
    image: record.stream:0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure:2
    #restart: unless-stopped
    ports:
      - "8000:8000"
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./config/icecast.xml:/etc/icecast.xml
      - ./config/darkice.cfg:/etc/darkice.cfg
      - ./logs/icecast/error.log:/var/log/icecast/error.log
      - ./logs/icecast/access.log:/var/log/icecast/access.log

